version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/timtosi/bully-algorithm
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Build binaries
          command: |
            make build
            chmod +x cmd/bully/bully
            chmod +x cmd/data-viz/data-viz 
      - persist_to_workspace:
          root: cmd
          paths:
            - bully/bully
            - data-viz/data-viz

  run-test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/timtosi/bully-algorithm
    environment:
      TEST_RESULTS: /tmp/test-results/go-test
    steps:
      - checkout
      - run:
          name: Set test metadata requirements
          command: |
            mkdir -p $TEST_RESULTS
            go get github.com/jstemmer/go-junit-report
      - run:
          name: Install dependencies
          command: make install
      - run:
          name: Run test suite
          command: |
              trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
              make test | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  deploy-image:
    machine: true
    working_directory: ~/.go_workspace/src/github.com/timtosi/bully-algorithm
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/cmd
      - run:
          name: Log Docker user
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build bully image
          command: |
            mv /tmp/cmd/bully build/docker/bully/
            cp cmd/bully/conf/bully.conf.yaml build/docker/bully/
            docker build -t timtosi/bully:$DOCKER_IMAGE_TAG build/docker/bully/
            docker build -t timtosi/bully:latest build/docker/bully/
      - run:
          name: Build data-viz image
          command: |
            mv /tmp/cmd/data-viz build/docker/data-viz/
            cp -r cmd/data-viz/assets build/docker/data-viz/
            docker build -t timtosi/data-viz:$DOCKER_IMAGE_TAG build/docker/data-viz/
            docker build -t timtosi/data-viz:latest build/docker/data-viz/
      - run:
          name: Push bully images to Docker Hub
          command: |
            docker push timtosi/bully:$DOCKER_IMAGE_TAG
            docker push timtosi/bully:latest
      - run:
          name: Push data-viz images to Docker Hub
          command: |
            docker push timtosi/data-viz:$DOCKER_IMAGE_TAG
            docker push timtosi/data-viz:latest

workflows:
  version: 2
  build-test:
    jobs:
      - run-test
      - build
      - deploy-image:
          context: deploy-dockerhub
          requires:
            - run-test
            - build
          filters:
            branches:
              only:
                - master
